### ISSUE TITLE
Small question regarding equation 5.8 in the book

### ISSUE THREAD

**Issue by StevenBm** [mikexcohen/Statistics_book#3]
Dear Mike,

For the sake of exercise, I tried to derive equation 5.9 from equations 5.7 and 5.8 in the book (the uniformly distributed numbers with a specified mean and standard deviation). I was curious why in equation 5.8 the variance was denoted as ((a-b)^2)/12 instead of ((b-a)^2)/12. It took me a while to figure out that naively taking the square root caused my derivation to be incorrect. 

Kind regards,
Steven

**Comment by mikexcohen** [comment]
Because the difference is squared, the numerator is the same regardless of whether you end up with (a-b)^2 or (b-a)^2 (because we only consider the positive square root). But I think changing it to (b-a) would be less confusing. However, I see now that there is an actual typo in Equation 8.28. I'll fix both of those and re-compile the book, although it will remain incorrect in your version...
Thanks for letting me know, Steven!

**Comment by StevenBm** [comment]
Thank you for your quick reaction! I indeed should have taken the positive square root when deriving 5.9. I really enjoyed going through this book. Thank you!
